name: crm_call_logger
description: "T2G CRM - Team Call Logger. Auto-captures incoming/outgoing calls and syncs to CRM."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.0
  call_log: ^5.0.5
  permission_handler: ^11.4.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
